import React from 'react'

const skiper1 = () => {
    return (
        <div>
            <div className="w-full"><div className="relative z-40 w-screen"><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"><button type="button" className="fc size-full rounded-2xl"><span className="fc ac size-full cursor-pointer transition-all ease-in-out active:scale-95"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" className="lucide lucide-command size-4" aria-hidden="true"><path d="M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3"></path></svg></span><span className="sr-only">Command + K</span></button><div data-slot="dialog-header" className="flex flex-col gap-2 text-center sm:text-left sr-only"><h2 id="radix-_R_j5ubt5tnbH1_" data-slot="dialog-title" className="text-lg font-semibold leading-none">Command Palette</h2><p id="radix-_R_j5ubt5tnbH2_" data-slot="dialog-description" className="text-muted-foreground text-sm">Search for a command to run...</p></div></div><div className="relative grid min-h-[100dvh]"><div id="preview" className="grid min-h-[100dvh] grid-cols-1 bg-muted relative z-10 h-full w-full rounded-3xl lg:min-h-full"><div className="relative flex h-full w-full flex-col justify-end overflow-hidden text-white"><div className="scale-200 absolute inset-0 left-0 md:scale-100"><canvas data-engine="three.js r178" width="1920" height="620" className="w-500 h-500"></canvas></div><div className="pointer-events-none absolute bottom-0 w-full w-screen p-10"><h1 className="font-geist mb-10 max-w-xl pr-3 text-4xl font-medium leading-[0.9] tracking-tighter md:text-5xl lg:text-6xl">Vercel's one-day event for developers and bussiness leaders</h1><div className="flex w-full flex-col items-start gap-5 lg:flex-row lg:justify-between"><div className="flex w-full items-center justify-between gap-12 uppercase lg:w-fit lg:justify-center"><p className="font-geist-mono w-fit text-sm">punjab, india <br />and online</p><p className="font-geist-mono w-fit text-sm">sep 1, 2025 <br /> the Moosa pind</p></div><div className="flex w-full flex-wrap items-center justify-between gap-12 uppercase lg:w-fit lg:justify-center"><p className="font-geist-mono w-fit text-sm">onilne <br /> free</p><p className="font-geist-mono w-fit text-sm">in person tickets <br /> $600</p><button className="font-geist-mono flex items-center gap-2 bg-white px-4 py-2 text-sm uppercase text-black">get tickets<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" className="lucide lucide-arrow-right h-4 w-4" aria-hidden="true"><path d="M5 12h14"></path><path d="m12 5 7 7-7 7"></path></svg></button></div></div></div></div></div></div></div></div>
        </div>
    )
}

export default skiper1